# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-SerialFork
version:      0.01
version_from: lib/Test/SerialFork.pm
installdirs:  site
requires:
    Test::Builder:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
